import Foundation

/// Root structure of xcstrings file
package struct XCStringsFile: Codable {
    var sourceLanguage: String
    var strings: [String: StringEntry]
    var version: String

    package init(sourceLanguage: String = "en", strings: [String: StringEntry] = [:], version: String = "1.0") {
        self.sourceLanguage = sourceLanguage
        self.strings = strings
        self.version = version
    }
}

/// String entry for each key
package struct StringEntry: Codable {
    var comment: String?
    var isCommentAutoGenerated: Bool?
    var extractionState: String?
    var shouldTranslate: Bool?
    var localizations: [String: Localization]?

    var requiresTranslation: Bool {
        shouldTranslate != false
    }

    package init(
        comment: String? = nil,
        isCommentAutoGenerated: Bool? = nil,
        extractionState: String? = nil,
        shouldTranslate: Bool? = nil,
        localizations: [String: Localization]? = nil
    ) {
        self.comment = comment
        self.isCommentAutoGenerated = isCommentAutoGenerated
        self.extractionState = extractionState
        self.shouldTranslate = shouldTranslate
        self.localizations = localizations
    }
}

/// Localization entry
package struct Localization: Codable {
    var stringUnit: StringUnit?
    var variations: Variations?

    package init(stringUnit: StringUnit? = nil, variations: Variations? = nil) {
        self.stringUnit = stringUnit
        self.variations = variations
    }
}

/// String unit containing the actual translation value
package struct StringUnit: Codable {
    var state: String
    var value: String

    package init(state: String = "translated", value: String) {
        self.state = state
        self.value = value
    }
}

/// Variations (plural, device, etc.)
package struct Variations: Codable {
    var plural: PluralVariation?
    var device: DeviceVariation?

    package init(plural: PluralVariation? = nil, device: DeviceVariation? = nil) {
        self.plural = plural
        self.device = device
    }

    var allValues: [VariationValue] {
        [
            plural?.zero,
            plural?.one,
            plural?.two,
            plural?.few,
            plural?.many,
            plural?.other,
            device?.iphone,
            device?.ipad,
            device?.mac,
            device?.applewatch,
            device?.appletv,
        ].compactMap(\.self)
    }
}

/// Wrapper for a variation category value (e.g. each plural form or device category)
/// In xcstrings JSON, each variation value is `{ "stringUnit": { "state": "...", "value": "..." } }`
package struct VariationValue: Codable {
    var stringUnit: StringUnit?

    package init(stringUnit: StringUnit? = nil) {
        self.stringUnit = stringUnit
    }
}

/// Plural variation
package struct PluralVariation: Codable {
    var zero: VariationValue?
    var one: VariationValue?
    var two: VariationValue?
    var few: VariationValue?
    var many: VariationValue?
    var other: VariationValue?

    package init(
        zero: VariationValue? = nil,
        one: VariationValue? = nil,
        two: VariationValue? = nil,
        few: VariationValue? = nil,
        many: VariationValue? = nil,
        other: VariationValue? = nil
    ) {
        self.zero = zero
        self.one = one
        self.two = two
        self.few = few
        self.many = many
        self.other = other
    }
}

/// Device variation
package struct DeviceVariation: Codable {
    var iphone: VariationValue?
    var ipad: VariationValue?
    var mac: VariationValue?
    var applewatch: VariationValue?
    var appletv: VariationValue?

    package init(
        iphone: VariationValue? = nil,
        ipad: VariationValue? = nil,
        mac: VariationValue? = nil,
        applewatch: VariationValue? = nil,
        appletv: VariationValue? = nil
    ) {
        self.iphone = iphone
        self.ipad = ipad
        self.mac = mac
        self.applewatch = applewatch
        self.appletv = appletv
    }
}

// MARK: - Output Models

/// Key information for output
package struct KeyInfo: Codable {
    package let key: String
    package let comment: String?
    package let isCommentAutoGenerated: Bool?
    package let extractionState: String?
    package let shouldTranslate: Bool?
    package let languages: [String]

    package init(
        key: String,
        comment: String?,
        isCommentAutoGenerated: Bool?,
        extractionState: String?,
        shouldTranslate: Bool?,
        languages: [String]
    ) {
        self.key = key
        self.comment = comment
        self.isCommentAutoGenerated = isCommentAutoGenerated
        self.extractionState = extractionState
        self.shouldTranslate = shouldTranslate
        self.languages = languages
    }
}

/// Translation information for output
package struct TranslationInfo: Codable {
    package let key: String
    package let language: String
    package let value: String?
    package let state: String?
    package let hasVariations: Bool

    package init(key: String, language: String, value: String?, state: String?, hasVariations: Bool) {
        self.key = key
        self.language = language
        self.value = value
        self.state = state
        self.hasVariations = hasVariations
    }
}

/// Coverage information for output
package struct CoverageInfo: Codable {
    package let key: String
    package let translatedLanguages: [String]
    package let missingLanguages: [String]
    package let coveragePercent: Double

    package init(key: String, translatedLanguages: [String], missingLanguages: [String], coveragePercent: Double) {
        self.key = key
        self.translatedLanguages = translatedLanguages
        self.missingLanguages = missingLanguages
        self.coveragePercent = coveragePercent
    }
}

/// Overall statistics for output
package struct StatsInfo: Codable {
    package let totalKeys: Int
    package let sourceLanguage: String
    package let languages: [String]
    package let coverageByLanguage: [String: LanguageStats]

    package init(totalKeys: Int, sourceLanguage: String, languages: [String], coverageByLanguage: [String: LanguageStats]) {
        self.totalKeys = totalKeys
        self.sourceLanguage = sourceLanguage
        self.languages = languages
        self.coverageByLanguage = coverageByLanguage
    }
}

/// Per-language statistics
package struct LanguageStats: Codable {
    package let translated: Int
    package let untranslated: Int
    package let total: Int
    package let coveragePercent: Double

    package init(translated: Int, untranslated: Int, total: Int, coveragePercent: Double) {
        self.translated = translated
        self.untranslated = untranslated
        self.total = total
        self.coveragePercent = coveragePercent
    }
}

/// A single untranslated entry found in an xcstrings file.
package struct UntranslatedIssue: Codable, Equatable {
    package let file: String
    package let language: String
    package let key: String
    package let reason: UntranslatedReason
    package let state: String?

    package init(file: String, language: String, key: String, reason: UntranslatedReason, state: String? = nil) {
        self.file = file
        self.language = language
        self.key = key
        self.reason = reason
        self.state = state
    }
}

/// Stable machine-readable reason for an untranslated issue.
package enum UntranslatedReason: String, Codable, Equatable {
    case missingLocalization
    case emptyValue
    case stateNotTranslated
    case missingStringUnit
    case missingVariationValues
    case missingVariationStringUnit
    case emptyVariationValue
    case variationStateNotTranslated

    package func message(state: String?) -> String {
        switch self {
        case .missingLocalization:
            "missing localization"
        case .emptyValue:
            "empty value"
        case .stateNotTranslated:
            "state is \(state ?? "unknown")"
        case .missingStringUnit:
            "missing string unit"
        case .missingVariationValues:
            "missing variation values"
        case .missingVariationStringUnit:
            "missing variation string unit"
        case .emptyVariationValue:
            "empty variation value"
        case .variationStateNotTranslated:
            "variation state is \(state ?? "unknown")"
        }
    }
}

/// Result of checking untranslated entries across one or more xcstrings files.
package struct UntranslatedCheckResult: Codable, Equatable {
    package let issues: [UntranslatedIssue]

    package var isComplete: Bool {
        issues.isEmpty
    }

    package init(issues: [UntranslatedIssue]) {
        self.issues = issues
    }
}

/// Token-efficient batch coverage summary for multiple files
package struct BatchCoverageSummary: Codable {
    package let files: [FileCoverageSummary]
    package let aggregated: AggregatedCoverage

    package init(files: [FileCoverageSummary], aggregated: AggregatedCoverage) {
        self.files = files
        self.aggregated = aggregated
    }
}

/// Compact coverage summary for a single file
package struct FileCoverageSummary: Codable {
    package let file: String
    package let totalKeys: Int
    package let languages: [String: Double] // lang -> coveragePercent

    package init(file: String, totalKeys: Int, languages: [String: Double]) {
        self.file = file
        self.totalKeys = totalKeys
        self.languages = languages
    }
}

/// Aggregated coverage across all files
package struct AggregatedCoverage: Codable {
    package let totalFiles: Int
    package let totalKeys: Int
    package let averageCoverageByLanguage: [String: Double]

    package init(totalFiles: Int, totalKeys: Int, averageCoverageByLanguage: [String: Double]) {
        self.totalFiles = totalFiles
        self.totalKeys = totalKeys
        self.averageCoverageByLanguage = averageCoverageByLanguage
    }
}

// MARK: - Compact Output Models (100% languages omitted)

/// Compact stats info - only shows languages under 100%
package struct CompactStatsInfo: Codable {
    package let totalKeys: Int
    package let sourceLanguage: String
    package let totalLanguages: Int
    package let allComplete: Bool
    package let incompleteLanguages: [String: LanguageStats]? // nil if all complete
    package let completeCount: Int // number of languages at 100%

    package init(from stats: StatsInfo) {
        totalKeys = stats.totalKeys
        sourceLanguage = stats.sourceLanguage
        totalLanguages = stats.languages.count

        let incomplete = stats.coverageByLanguage.filter { $0.value.coveragePercent < 100 }
        allComplete = incomplete.isEmpty
        incompleteLanguages = incomplete.isEmpty ? nil : incomplete
        completeCount = stats.coverageByLanguage.count - incomplete.count
    }
}

/// Compact file coverage summary - only shows languages under 100%
package struct CompactFileCoverageSummary: Codable {
    package let file: String
    package let totalKeys: Int
    package let totalLanguages: Int
    package let allComplete: Bool
    package let incompleteLanguages: [String: Double]? // nil if all complete
    package let completeCount: Int

    package init(from summary: FileCoverageSummary) {
        file = summary.file
        totalKeys = summary.totalKeys
        totalLanguages = summary.languages.count

        let incomplete = summary.languages.filter { $0.value < 100 }
        allComplete = incomplete.isEmpty
        incompleteLanguages = incomplete.isEmpty ? nil : incomplete
        completeCount = summary.languages.count - incomplete.count
    }
}

/// Compact batch coverage summary
package struct CompactBatchCoverageSummary: Codable {
    package let files: [CompactFileCoverageSummary]
    package let aggregated: CompactAggregatedCoverage

    package init(from batch: BatchCoverageSummary) {
        files = batch.files.map { CompactFileCoverageSummary(from: $0) }
        aggregated = CompactAggregatedCoverage(from: batch.aggregated)
    }
}

/// Compact aggregated coverage
package struct CompactAggregatedCoverage: Codable {
    package let totalFiles: Int
    package let totalKeys: Int
    package let totalLanguages: Int
    package let allComplete: Bool
    package let incompleteLanguages: [String: Double]?
    package let completeCount: Int

    package init(from agg: AggregatedCoverage) {
        totalFiles = agg.totalFiles
        totalKeys = agg.totalKeys
        totalLanguages = agg.averageCoverageByLanguage.count

        let incomplete = agg.averageCoverageByLanguage.filter { $0.value < 100 }
        allComplete = incomplete.isEmpty
        incompleteLanguages = incomplete.isEmpty ? nil : incomplete
        completeCount = agg.averageCoverageByLanguage.count - incomplete.count
    }
}

// MARK: - Batch Operation Models

/// Result of batch key existence check
package struct BatchCheckKeysResult: Codable {
    package let results: [String: Bool] // key -> exists
    package let existingKeys: [String]
    package let missingKeys: [String]

    package init(results: [String: Bool]) {
        self.results = results
        existingKeys = results.filter(\.value).keys.sorted()
        missingKeys = results.filter { !$0.value }.keys.sorted()
    }
}

/// Single entry for batch add/update operations
package struct BatchTranslationEntry: Codable {
    package let key: String
    package let translations: [String: String] // language -> value

    package init(key: String, translations: [String: String]) {
        self.key = key
        self.translations = translations
    }
}

/// Result of batch add/update operations
package struct BatchWriteResult: Codable {
    package let success: Bool
    package let successCount: Int
    package let failedCount: Int
    package let succeeded: [String]
    package let failed: [BatchWriteError]

    package init(succeeded: [String], failed: [BatchWriteError]) {
        success = failed.isEmpty
        successCount = succeeded.count
        failedCount = failed.count
        self.succeeded = succeeded
        self.failed = failed
    }

    private enum CodingKeys: String, CodingKey {
        case success, successCount, failedCount, succeeded, failed
    }

    package func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encode(successCount, forKey: .successCount)
        try container.encode(failedCount, forKey: .failedCount)
        // Only include non-empty arrays
        if !succeeded.isEmpty {
            try container.encode(succeeded, forKey: .succeeded)
        }
        if !failed.isEmpty {
            try container.encode(failed, forKey: .failed)
        }
    }
}

/// Error info for batch write operations
package struct BatchWriteError: Codable {
    package let key: String
    package let error: String

    package init(key: String, error: String) {
        self.key = key
        self.error = error
    }
}

// MARK: - Stale Keys Models

/// Constants for stale keys messages
package enum StaleKeysConstants {
    package static let note = "These keys are marked as 'stale' by Xcode, indicating they may no longer be used in source code. Please verify by searching for these keys in the module or project source code before deleting them."
}

/// Stale keys for a single file
package struct FileStaleKeysSummary: Codable {
    package let file: String
    package let staleKeys: [String]
    package let count: Int

    package init(file: String, staleKeys: [String]) {
        self.file = file
        self.staleKeys = staleKeys
        count = staleKeys.count
    }
}

/// Stale keys result for a single file
package struct StaleKeysResult: Codable {
    package let staleKeys: [String]
    package let count: Int
    package let note: String

    package init(staleKeys: [String]) {
        self.staleKeys = staleKeys
        count = staleKeys.count
        note = StaleKeysConstants.note
    }
}

/// Batch stale keys summary for multiple files
package struct BatchStaleKeysSummary: Codable {
    package let files: [FileStaleKeysSummary]
    package let totalStaleKeys: Int
    package let note: String

    package init(files: [FileStaleKeysSummary]) {
        self.files = files
        totalStaleKeys = files.reduce(0) { $0 + $1.count }
        note = StaleKeysConstants.note
    }
}
