import Foundation

/// Handles read operations for xcstrings files
struct XCStringsReader {
    private let file: XCStringsFile

    init(file: XCStringsFile) {
        self.file = file
    }

    /// Get all keys sorted alphabetically
    func listKeys() -> [String] {
        XCStringsKeySorter.sort(file.strings.keys)
    }

    /// Get all languages used in the file
    func listLanguages() -> [String] {
        file.strings.values.lazy
            .compactMap(\.localizations?.keys)
            .reduce(into: Set([file.sourceLanguage])) { $0.formUnion($1) }
            .sorted()
    }

    /// Get untranslated keys for a specific language
    func listUntranslated(for language: String) -> [String] {
        file.strings
            .filter { _, entry in
                guard entry.requiresTranslation else {
                    return false
                }

                let localization = entry.localizations?[language]
                return localization?.stringUnit?.value == nil && localization?.variations == nil
            }
            .keys
            .withXcodeSort()
    }

    /// Check untranslated entries for hook/CI usage.
    func checkUntranslated(file path: String, languages: [String]) -> [UntranslatedIssue] {
        let sortedLanguages = Set(languages).sorted()
        let sortedKeys = file.strings.keys.withXcodeSort()

        return sortedLanguages.flatMap { language in
            sortedKeys.compactMap { key in
                guard let entry = file.strings[key], entry.requiresTranslation else { return nil }
                return untranslatedIssue(
                    file: path,
                    language: language,
                    key: key,
                    localization: entry.localizations?[language]
                )
            }
        }
    }

    /// Get keys with stale extraction state
    func listStaleKeys() -> [String] {
        file.strings
            .filter { $0.value.extractionState == "stale" }
            .map(\.key)
            .withXcodeSort()
    }

    /// Get source language
    func getSourceLanguage() -> String {
        file.sourceLanguage
    }

    /// Find keys whose NFKC-normalized form matches the given key's NFKC-normalized form.
    /// Used to surface suggestions when a key is not found due to visually identical
    /// but Unicode-distinct characters (e.g. U+0027 vs U+2019 apostrophes).
    func suggestions(for key: String) -> [String] {
        let normalized = key.precomposedStringWithCompatibilityMapping
        return file.strings.keys
            .filter { $0 != key && $0.precomposedStringWithCompatibilityMapping == normalized }
            .withXcodeSort()
    }

    /// Get key information
    func getKey(_ key: String) throws -> KeyInfo {
        guard let entry = file.strings[key] else {
            throw XCStringsError.keyNotFound(key: key, suggestions: suggestions(for: key))
        }

        let languages = entry.localizations?.keys.sorted() ?? []

        return KeyInfo(
            key: key,
            comment: entry.comment,
            isCommentAutoGenerated: entry.isCommentAutoGenerated,
            extractionState: entry.extractionState,
            shouldTranslate: entry.shouldTranslate,
            languages: languages
        )
    }

    /// Get translation for a key
    func getTranslation(key: String, language: String?) throws -> [String: TranslationInfo] {
        guard let entry = file.strings[key] else {
            throw XCStringsError.keyNotFound(key: key, suggestions: suggestions(for: key))
        }

        var result: [String: TranslationInfo] = [:]

        if let lang = language {
            if let localization = entry.localizations?[lang] {
                result[lang] = TranslationInfo(
                    key: key,
                    language: lang,
                    value: localization.stringUnit?.value,
                    state: localization.stringUnit?.state,
                    hasVariations: localization.variations != nil
                )
            } else {
                throw XCStringsError.languageNotFound(language: lang, key: key)
            }
        } else if let localizations = entry.localizations {
            result = Dictionary(uniqueKeysWithValues: localizations.map { lang, localization in
                (lang, TranslationInfo(
                    key: key,
                    language: lang,
                    value: localization.stringUnit?.value,
                    state: localization.stringUnit?.state,
                    hasVariations: localization.variations != nil
                ))
            })
        }

        return result
    }

    /// Check if a key exists
    func checkKey(_ key: String, language: String?) -> Bool {
        guard let entry = file.strings[key] else {
            return false
        }

        if let lang = language {
            return entry.localizations?[lang] != nil
        }

        return true
    }

    /// Check if multiple keys exist
    func checkKeys(_ keys: [String], language: String?) -> BatchCheckKeysResult {
        let results = Dictionary(uniqueKeysWithValues: keys.lazy.map { ($0, checkKey($0, language: language)) })
        return BatchCheckKeysResult(results: results)
    }

    /// Check coverage for a key
    func checkCoverage(_ key: String) throws -> CoverageInfo {
        let allLanguages = listLanguages()

        guard let entry = file.strings[key] else {
            throw XCStringsError.keyNotFound(key: key, suggestions: suggestions(for: key))
        }

        guard entry.requiresTranslation else {
            return CoverageInfo(
                key: key,
                translatedLanguages: [],
                missingLanguages: [],
                coveragePercent: 100
            )
        }

        let translatedLanguages = entry.localizations?.keys.sorted() ?? []
        let missingLanguages = allLanguages.filter { !translatedLanguages.contains($0) }
        let coveragePercent = allLanguages.isEmpty
            ? 0
            : Double(translatedLanguages.count) / Double(allLanguages.count) * 100

        return CoverageInfo(
            key: key,
            translatedLanguages: translatedLanguages,
            missingLanguages: missingLanguages,
            coveragePercent: coveragePercent
        )
    }

    private func untranslatedIssue(file: String, language: String, key: String, localization: Localization?) -> UntranslatedIssue? {
        guard let localization else {
            return UntranslatedIssue(file: file, language: language, key: key, reason: .missingLocalization)
        }

        if let stringUnit = localization.stringUnit {
            if stringUnit.value.isEmpty {
                return UntranslatedIssue(file: file, language: language, key: key, reason: .emptyValue)
            }
            if stringUnit.state != "translated" {
                return UntranslatedIssue(file: file, language: language, key: key, reason: .stateNotTranslated, state: stringUnit.state)
            }
            return nil
        }

        if let variations = localization.variations {
            return untranslatedVariationIssue(file: file, language: language, key: key, variations: variations)
        }

        return UntranslatedIssue(file: file, language: language, key: key, reason: .missingStringUnit)
    }

    private func untranslatedVariationIssue(file: String, language: String, key: String, variations: Variations) -> UntranslatedIssue? {
        let values = variations.allValues

        guard !values.isEmpty else {
            return UntranslatedIssue(file: file, language: language, key: key, reason: .missingVariationValues)
        }

        for value in values {
            guard let stringUnit = value.stringUnit else {
                return UntranslatedIssue(file: file, language: language, key: key, reason: .missingVariationStringUnit)
            }
            if stringUnit.value.isEmpty {
                return UntranslatedIssue(file: file, language: language, key: key, reason: .emptyVariationValue)
            }
            if stringUnit.state != "translated" {
                return UntranslatedIssue(file: file, language: language, key: key, reason: .variationStateNotTranslated, state: stringUnit.state)
            }
        }

        return nil
    }
}
